import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className + " h-screen"}>
        <div className="h-full bg-slate-800 flex flex-col justify-between">
          <Header />
          <div className="rounded-3xl bg-slate-50 h-full">
            {children}
          </div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
