import type { Metadata } from "next";
import { Inter, IBM_Plex_Sans_Thai } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });
const ibmPlexSansThaiLooped = IBM_Plex_Sans_Thai({
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  subsets: ["thai"],
  variable: "--ibm-plex-sans-thai-font",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          inter.className,
          ibmPlexSansThaiLooped.className,
          "h-full",
        )}
      >
        <Toaster
          position="bottom-right"
          toastOptions={{
            className: "font-semibold bg-white text-slate-800",
            success: {
              iconTheme: {
                primary: "#1e293b",
                secondary: "white",
              },
            },
          }}
        />
        {children}
      </body>
    </html>
  );
}
