name: Production Next.js CI/CD

on:
  pull_request:
    types:
      - closed
    branches:
      - main

env:
  REGION: us-central1

jobs:
  build-and-deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - id: auth
        name: Auth with GCP
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Create env File 
        run: |
          touch .env
          echo DATABASE_URL=${{ secrets.DATABASE_URL }} >> .env

      - name: Configure Docker
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build and Push to Artifact Registry
        run: |
          docker image prune -a
          docker build \
            --build-arg DATABASE_URL=${{ secrets.DATABASE_URL }} \
            -t ${{ secrets.GCP_PROD_NEXTJS_AR_LOCATION }} .
          docker push ${{ secrets.GCP_PROD_NEXTJS_AR_LOCATION }}

      - id: deploy
        name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          image: ${{ secrets.GCP_PROD_NEXTJS_AR_LOCATION }}
          service: ${{ secrets.GCP_PROD_NEXTJS_CR_NAME }}
          region: ${{ env.REGION }}
      
      - name: Use output
        run: curl ${{ steps.deploy.outputs.url }}

  discord-noti:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Discord Notification
        uses: Sniddl/discord-commits@v1.6
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          message: "<@&1085297978266353694> main มีการอัปเดทแล้ว ไป pull แล้ว merge กันด้วย ก่อนที่จะโดนหมับหน้าเข้าให้ \nPR Title: ${{ github.event.pull_request.title }} \nPR Author: ${{ github.event.pull_request.user.login }} \nPR head branch: ${{ github.head_ref }} \nPR Link: https://github.com/SoeiCorp/skillbridge/pull/${{ github.event.number }}"
